version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  brightocean-api:
    build: .
    container_name: brightocean-api
    environment:
      SPRING_CONFIG_LOCATION: /app/application-docker.properties
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./application-docker.properties:/app/application-docker.properties

volumes:
  mysql-data:
