### ATENÇÃO ####
# AO USAR A VERSÃO 4.27.1 DO DOCKER DESKTOP
# PRECISEI SETAR UMA VARIAVEL DE AMBIENTE DOCKER_BUILDKIT COM O VALOR 0 (SET DOCKER_BUILDKIT=0)
# DEVIDO AO UM BUG DO DOCKER QUE FOI RESOLVIDO NAS ÚLTIMAS VERSÕES

version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: brightocean_mysql
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  brightocean-image:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brightocean-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/brightocean_mysql
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

volumes:
  mysql-data: